"""RetiroFlow demo data — realistic Oaxaca wellness retreat dataset."""

from __future__ import annotations

from datetime import date, datetime

from .store import save_store


def seed_demo_data() -> dict:
    """Generate and persist all demo data. Returns the full store dict."""

    centers = [
        {
            "id": "ctr-mazunte-01",
            "name": "Hridaya Yoga Center",
            "location": "mazunte",
            "type": "yoga",
            "capacity": 40,
            "price_range_usd": {"min": 120, "max": 280},
            "amenities": ["pool", "ocean_view", "organic_garden", "wifi", "library"],
            "languages": ["es", "en", "fr"],
            "certifications": ["Yoga Alliance RYS-200", "Yoga Alliance RYS-500"],
            "rating": 4.8,
            "photos": [],
            "owner": "Maria Elena Vasquez",
            "contact": "+52-958-100-0101",
            "created_at": "2024-01-15T00:00:00",
        },
        {
            "id": "ctr-mazunte-02",
            "name": "Solstice Retreat Mazunte",
            "location": "mazunte",
            "type": "mixed",
            "capacity": 25,
            "price_range_usd": {"min": 150, "max": 350},
            "amenities": ["temazcal", "ocean_view", "organic_meals", "wifi", "jungle_trails"],
            "languages": ["es", "en"],
            "certifications": ["COFEPRIS Health License"],
            "rating": 4.6,
            "photos": [],
            "owner": "Carlos Mendez",
            "contact": "+52-958-100-0102",
            "created_at": "2024-03-10T00:00:00",
        },
        {
            "id": "ctr-zipolite-01",
            "name": "Casa Cosmos Zipolite",
            "location": "zipolite",
            "type": "meditation",
            "capacity": 20,
            "price_range_usd": {"min": 80, "max": 200},
            "amenities": ["meditation_hall", "beach_access", "organic_garden", "hammocks"],
            "languages": ["es", "en"],
            "certifications": ["Vipassana Certified"],
            "rating": 4.7,
            "photos": [],
            "owner": "Ana Luz Reyes",
            "contact": "+52-958-100-0103",
            "created_at": "2024-02-20T00:00:00",
        },
        {
            "id": "ctr-hierve-01",
            "name": "Agua Sagrada Retreat",
            "location": "hierve_el_agua",
            "type": "healing",
            "capacity": 15,
            "price_range_usd": {"min": 100, "max": 250},
            "amenities": ["mineral_springs", "mountain_view", "ceremony_space", "organic_meals"],
            "languages": ["es", "en", "zapotec"],
            "certifications": ["Traditional Healer Network"],
            "rating": 4.9,
            "photos": [],
            "owner": "Don Aurelio Cruz",
            "contact": "+52-951-100-0104",
            "created_at": "2023-11-05T00:00:00",
        },
        {
            "id": "ctr-sanjose-01",
            "name": "Nube Sagrada Mountain Retreat",
            "location": "san_jose_del_pacifico",
            "type": "ayahuasca",
            "capacity": 12,
            "price_range_usd": {"min": 200, "max": 500},
            "amenities": ["ceremony_space", "cloud_forest", "fireplace", "stargazing_deck"],
            "languages": ["es", "en", "mazatec"],
            "certifications": ["Traditional Medicine Practitioner"],
            "rating": 4.5,
            "photos": [],
            "owner": "Dona Lupita Hernandez",
            "contact": "+52-951-100-0105",
            "created_at": "2024-04-01T00:00:00",
        },
        {
            "id": "ctr-oaxaca-01",
            "name": "Centro Bienestar Oaxaca",
            "location": "oaxaca_city",
            "type": "wellness_spa",
            "capacity": 30,
            "price_range_usd": {"min": 90, "max": 220},
            "amenities": ["spa", "rooftop_terrace", "mezcal_bar", "cooking_class", "wifi"],
            "languages": ["es", "en"],
            "certifications": ["COFEPRIS Health License", "Green Globe"],
            "rating": 4.4,
            "photos": [],
            "owner": "Ricardo Bautista",
            "contact": "+52-951-100-0106",
            "created_at": "2024-05-12T00:00:00",
        },
        {
            "id": "ctr-montealban-01",
            "name": "Ancestral Healing Monte Alban",
            "location": "monte_alban_area",
            "type": "temazcal",
            "capacity": 18,
            "price_range_usd": {"min": 70, "max": 180},
            "amenities": ["temazcal", "sacred_grounds", "herb_garden", "traditional_kitchen"],
            "languages": ["es", "zapotec"],
            "certifications": ["Indigenous Healers Cooperative"],
            "rating": 4.8,
            "photos": [],
            "owner": "Maestra Sofia Jimenez",
            "contact": "+52-951-100-0107",
            "created_at": "2023-09-20T00:00:00",
        },
        {
            "id": "ctr-huatulco-01",
            "name": "Bahias Wellness Huatulco",
            "location": "huatulco",
            "type": "wellness_spa",
            "capacity": 50,
            "price_range_usd": {"min": 180, "max": 450},
            "amenities": ["infinity_pool", "spa", "beach_club", "restaurant", "gym", "wifi"],
            "languages": ["es", "en", "de"],
            "certifications": ["Yoga Alliance RYS-200", "COFEPRIS Health License"],
            "rating": 4.3,
            "photos": [],
            "owner": "Johann Schmidt",
            "contact": "+52-958-100-0108",
            "created_at": "2024-06-01T00:00:00",
        },
        {
            "id": "ctr-mazunte-03",
            "name": "Templo del Viento",
            "location": "mazunte",
            "type": "yoga",
            "capacity": 22,
            "price_range_usd": {"min": 100, "max": 240},
            "amenities": ["shala", "ocean_view", "jungle_huts", "composting_toilets"],
            "languages": ["es", "en"],
            "certifications": ["Yoga Alliance RYS-200"],
            "rating": 4.6,
            "photos": [],
            "owner": "Daniela Rojas",
            "contact": "+52-958-100-0109",
            "created_at": "2024-07-15T00:00:00",
        },
        {
            "id": "ctr-zipolite-02",
            "name": "Playa del Alma",
            "location": "zipolite",
            "type": "mixed",
            "capacity": 16,
            "price_range_usd": {"min": 90, "max": 210},
            "amenities": ["beach_access", "yoga_deck", "temazcal", "organic_meals"],
            "languages": ["es", "en", "it"],
            "certifications": [],
            "rating": 4.4,
            "photos": [],
            "owner": "Marco Rossi",
            "contact": "+52-958-100-0110",
            "created_at": "2024-08-01T00:00:00",
        },
        {
            "id": "ctr-sanjose-02",
            "name": "Cielo Abierto",
            "location": "san_jose_del_pacifico",
            "type": "meditation",
            "capacity": 10,
            "price_range_usd": {"min": 80, "max": 190},
            "amenities": ["cloud_forest", "silence_zone", "fireplace", "library"],
            "languages": ["es", "en"],
            "certifications": ["Vipassana Certified"],
            "rating": 4.7,
            "photos": [],
            "owner": "Patricia Morales",
            "contact": "+52-951-100-0111",
            "created_at": "2024-09-10T00:00:00",
        },
        {
            "id": "ctr-oaxaca-02",
            "name": "Xocolatl Healing House",
            "location": "oaxaca_city",
            "type": "healing",
            "capacity": 14,
            "price_range_usd": {"min": 110, "max": 260},
            "amenities": ["cacao_ceremony_room", "herb_garden", "rooftop", "traditional_kitchen"],
            "languages": ["es", "en"],
            "certifications": ["Traditional Healer Network"],
            "rating": 4.6,
            "photos": [],
            "owner": "Elena Ruiz",
            "contact": "+52-951-100-0112",
            "created_at": "2024-10-01T00:00:00",
        },
    ]

    retreats = [
        {"id": "ret-001", "center_id": "ctr-mazunte-01", "name": "7-Day Hridaya Silent Yoga Retreat", "description": "Deep immersion in Hridaya yoga with daily meditation, asana, and pranayama. Silence observed from day 2.", "type": "yoga", "start_date": "2026-04-14", "end_date": "2026-04-20", "duration_days": 7, "price_usd": 1400, "max_participants": 25, "current_participants": 18, "facilitator_ids": ["fac-001", "fac-002"], "status": "upcoming", "meals_included": True, "accommodation_type": "shared"},
        {"id": "ret-002", "center_id": "ctr-zipolite-01", "name": "Weekend Vipassana Meditation", "description": "48-hour silent Vipassana meditation intensive on the Oaxacan coast.", "type": "meditation", "start_date": "2026-04-11", "end_date": "2026-04-13", "duration_days": 3, "price_usd": 450, "max_participants": 15, "current_participants": 12, "facilitator_ids": ["fac-003"], "status": "upcoming", "meals_included": True, "accommodation_type": "shared"},
        {"id": "ret-003", "center_id": "ctr-hierve-01", "name": "Zapotec Healing Ceremony Retreat", "description": "4-day immersion in traditional Zapotec healing practices at the sacred mineral springs.", "type": "healing", "start_date": "2026-04-18", "end_date": "2026-04-21", "duration_days": 4, "price_usd": 800, "max_participants": 12, "current_participants": 9, "facilitator_ids": ["fac-004", "fac-005"], "status": "upcoming", "meals_included": True, "accommodation_type": "shared"},
        {"id": "ret-004", "center_id": "ctr-montealban-01", "name": "Temazcal Purification Weekend", "description": "Two temazcal ceremonies with herb preparation workshops and traditional Oaxacan cuisine.", "type": "temazcal", "start_date": "2026-04-25", "end_date": "2026-04-27", "duration_days": 3, "price_usd": 350, "max_participants": 15, "current_participants": 11, "facilitator_ids": ["fac-006"], "status": "upcoming", "meals_included": True, "accommodation_type": "shared"},
        {"id": "ret-005", "center_id": "ctr-sanjose-01", "name": "Plant Medicine Vision Quest", "description": "5-day guided ceremonial retreat in the cloud forests of San Jose del Pacifico.", "type": "ayahuasca", "start_date": "2026-05-02", "end_date": "2026-05-06", "duration_days": 5, "price_usd": 2200, "max_participants": 8, "current_participants": 6, "facilitator_ids": ["fac-007", "fac-008"], "status": "upcoming", "meals_included": True, "accommodation_type": "private"},
        {"id": "ret-006", "center_id": "ctr-oaxaca-01", "name": "Oaxacan Wellness Detox Week", "description": "7-day detox combining yoga, traditional Oaxacan superfoods, temazcal, and spa treatments.", "type": "wellness_spa", "start_date": "2026-04-07", "end_date": "2026-04-13", "duration_days": 7, "price_usd": 1600, "max_participants": 20, "current_participants": 14, "facilitator_ids": ["fac-009", "fac-010"], "status": "active", "meals_included": True, "accommodation_type": "private"},
        {"id": "ret-007", "center_id": "ctr-mazunte-03", "name": "5-Day Breathwork Intensive", "description": "Holotropic and Wim Hof breathwork combined with ocean swims and yoga.", "type": "yoga", "start_date": "2026-04-21", "end_date": "2026-04-25", "duration_days": 5, "price_usd": 950, "max_participants": 18, "current_participants": 10, "facilitator_ids": ["fac-011"], "status": "upcoming", "meals_included": True, "accommodation_type": "shared"},
        {"id": "ret-008", "center_id": "ctr-huatulco-01", "name": "Luxury Beach Yoga & Spa Retreat", "description": "10-day premium wellness retreat with daily yoga, spa treatments, and excursions.", "type": "wellness_spa", "start_date": "2026-04-15", "end_date": "2026-04-24", "duration_days": 10, "price_usd": 3500, "max_participants": 30, "current_participants": 22, "facilitator_ids": ["fac-001", "fac-012"], "status": "upcoming", "meals_included": True, "accommodation_type": "luxury"},
        {"id": "ret-009", "center_id": "ctr-mazunte-02", "name": "Cacao & Sound Healing Journey", "description": "3-day ceremonial cacao and sound healing immersion under the Mazunte stars.", "type": "mixed", "start_date": "2026-05-09", "end_date": "2026-05-11", "duration_days": 3, "price_usd": 550, "max_participants": 20, "current_participants": 8, "facilitator_ids": ["fac-013", "fac-014"], "status": "upcoming", "meals_included": True, "accommodation_type": "shared"},
        {"id": "ret-010", "center_id": "ctr-sanjose-02", "name": "10-Day Mountain Silence Retreat", "description": "Extended silent meditation in the cloud forests. Noble silence observed throughout.", "type": "meditation", "start_date": "2026-05-15", "end_date": "2026-05-24", "duration_days": 10, "price_usd": 1200, "max_participants": 10, "current_participants": 4, "facilitator_ids": ["fac-003"], "status": "upcoming", "meals_included": True, "accommodation_type": "shared"},
        {"id": "ret-011", "center_id": "ctr-oaxaca-02", "name": "Traditional Oaxacan Healing Arts", "description": "5-day deep dive into cacao ceremony, herbal medicine, and limpia cleansings.", "type": "healing", "start_date": "2026-04-28", "end_date": "2026-05-02", "duration_days": 5, "price_usd": 750, "max_participants": 14, "current_participants": 10, "facilitator_ids": ["fac-005", "fac-015"], "status": "upcoming", "meals_included": True, "accommodation_type": "shared"},
        {"id": "ret-012", "center_id": "ctr-zipolite-02", "name": "Surf & Yoga Beach Retreat", "description": "7-day beach lifestyle retreat combining morning yoga, surf lessons, and evening meditation.", "type": "mixed", "start_date": "2026-04-14", "end_date": "2026-04-20", "duration_days": 7, "price_usd": 1100, "max_participants": 16, "current_participants": 13, "facilitator_ids": ["fac-002", "fac-011"], "status": "upcoming", "meals_included": True, "accommodation_type": "shared"},
        {"id": "ret-013", "center_id": "ctr-mazunte-01", "name": "21-Day Yoga Teacher Training", "description": "RYS-200 certified yoga teacher training with Hridaya methodology.", "type": "yoga", "start_date": "2026-05-01", "end_date": "2026-05-21", "duration_days": 21, "price_usd": 3200, "max_participants": 20, "current_participants": 16, "facilitator_ids": ["fac-001", "fac-002", "fac-009"], "status": "upcoming", "meals_included": True, "accommodation_type": "shared"},
        {"id": "ret-014", "center_id": "ctr-hierve-01", "name": "New Moon Healing Circle", "description": "Weekend ceremony timed with the new moon at the sacred mineral springs.", "type": "healing", "start_date": "2026-04-12", "end_date": "2026-04-13", "duration_days": 2, "price_usd": 280, "max_participants": 12, "current_participants": 12, "facilitator_ids": ["fac-004"], "status": "upcoming", "meals_included": True, "accommodation_type": "camping"},
        {"id": "ret-015", "center_id": "ctr-montealban-01", "name": "Ancestral Medicine Apprenticeship", "description": "14-day apprenticeship in traditional Zapotec herbal medicine and temazcal.", "type": "temazcal", "start_date": "2026-05-10", "end_date": "2026-05-23", "duration_days": 14, "price_usd": 2800, "max_participants": 8, "current_participants": 3, "facilitator_ids": ["fac-006", "fac-004"], "status": "upcoming", "meals_included": True, "accommodation_type": "shared"},
        {"id": "ret-016", "center_id": "ctr-mazunte-02", "name": "Women's Circle Retreat", "description": "4-day women-only retreat: cacao ceremony, temazcal, dance, and sharing circles.", "type": "mixed", "start_date": "2026-05-07", "end_date": "2026-05-10", "duration_days": 4, "price_usd": 680, "max_participants": 15, "current_participants": 7, "facilitator_ids": ["fac-013", "fac-009"], "status": "upcoming", "meals_included": True, "accommodation_type": "shared"},
        {"id": "ret-017", "center_id": "ctr-huatulco-01", "name": "Corporate Wellness Weekend", "description": "Team-building wellness retreat with yoga, meditation, cooking class, and excursions.", "type": "wellness_spa", "start_date": "2026-04-19", "end_date": "2026-04-20", "duration_days": 2, "price_usd": 600, "max_participants": 40, "current_participants": 28, "facilitator_ids": ["fac-010", "fac-012"], "status": "upcoming", "meals_included": True, "accommodation_type": "luxury"},
        {"id": "ret-018", "center_id": "ctr-oaxaca-01", "name": "Mezcal & Mindfulness Experience", "description": "3-day unique blend of mezcal tasting, cooking classes, and mindfulness practices.", "type": "wellness_spa", "start_date": "2026-04-25", "end_date": "2026-04-27", "duration_days": 3, "price_usd": 520, "max_participants": 15, "current_participants": 11, "facilitator_ids": ["fac-010"], "status": "upcoming", "meals_included": True, "accommodation_type": "private"},
        {"id": "ret-019", "center_id": "ctr-mazunte-01", "name": "Spring Equinox Yoga Festival", "description": "3-day yoga festival with multiple teachers, live music, and beach ceremonies.", "type": "yoga", "start_date": "2026-03-20", "end_date": "2026-03-22", "duration_days": 3, "price_usd": 400, "max_participants": 40, "current_participants": 38, "facilitator_ids": ["fac-001", "fac-002", "fac-011"], "status": "completed", "meals_included": True, "accommodation_type": "camping"},
        {"id": "ret-020", "center_id": "ctr-zipolite-01", "name": "Full Moon Meditation Night", "description": "Overnight full moon meditation and sound bath on the beach.", "type": "meditation", "start_date": "2026-04-05", "end_date": "2026-04-06", "duration_days": 1, "price_usd": 120, "max_participants": 20, "current_participants": 20, "facilitator_ids": ["fac-003", "fac-014"], "status": "completed", "meals_included": False, "accommodation_type": "camping"},
    ]

    participants = [
        {"id": "par-001", "name": "Sarah Mitchell", "email": "sarah.m@email.com", "country": "US", "dietary_restrictions": ["vegan"], "medical_conditions": [], "experience_level": "intermediate", "retreat_ids": ["ret-001", "ret-019"], "total_spent_usd": 1800.0},
        {"id": "par-002", "name": "James Thornton", "email": "james.t@email.com", "country": "US", "dietary_restrictions": [], "medical_conditions": ["bad_knees"], "experience_level": "beginner", "retreat_ids": ["ret-006"], "total_spent_usd": 1600.0},
        {"id": "par-003", "name": "Emma van der Berg", "email": "emma.vdb@email.com", "country": "NL", "dietary_restrictions": ["vegetarian"], "medical_conditions": [], "experience_level": "advanced", "retreat_ids": ["ret-001", "ret-013"], "total_spent_usd": 4600.0},
        {"id": "par-004", "name": "Lucas Dubois", "email": "lucas.d@email.com", "country": "FR", "dietary_restrictions": [], "medical_conditions": [], "experience_level": "intermediate", "retreat_ids": ["ret-002"], "total_spent_usd": 450.0},
        {"id": "par-005", "name": "Maria Garcia", "email": "maria.g@email.com", "country": "MX", "dietary_restrictions": [], "medical_conditions": [], "experience_level": "advanced", "retreat_ids": ["ret-003", "ret-014"], "total_spent_usd": 1080.0},
        {"id": "par-006", "name": "David Chen", "email": "david.c@email.com", "country": "CA", "dietary_restrictions": ["gluten_free"], "medical_conditions": ["asthma"], "experience_level": "beginner", "retreat_ids": ["ret-008"], "total_spent_usd": 3500.0},
        {"id": "par-007", "name": "Olivia Johnson", "email": "olivia.j@email.com", "country": "US", "dietary_restrictions": ["vegan", "raw"], "medical_conditions": [], "experience_level": "advanced", "retreat_ids": ["ret-005"], "total_spent_usd": 2200.0},
        {"id": "par-008", "name": "Hans Mueller", "email": "hans.m@email.com", "country": "DE", "dietary_restrictions": [], "medical_conditions": [], "experience_level": "intermediate", "retreat_ids": ["ret-008", "ret-017"], "total_spent_usd": 4100.0},
        {"id": "par-009", "name": "Isabella Rossi", "email": "isabella.r@email.com", "country": "IT", "dietary_restrictions": ["vegetarian"], "medical_conditions": [], "experience_level": "beginner", "retreat_ids": ["ret-012"], "total_spent_usd": 1100.0},
        {"id": "par-010", "name": "Michael Brown", "email": "michael.b@email.com", "country": "US", "dietary_restrictions": [], "medical_conditions": ["back_pain"], "experience_level": "beginner", "retreat_ids": ["ret-006", "ret-018"], "total_spent_usd": 2120.0},
        {"id": "par-011", "name": "Sophie Laurent", "email": "sophie.l@email.com", "country": "FR", "dietary_restrictions": ["pescatarian"], "medical_conditions": [], "experience_level": "intermediate", "retreat_ids": ["ret-001"], "total_spent_usd": 1400.0},
        {"id": "par-012", "name": "Carlos Ramirez", "email": "carlos.r@email.com", "country": "MX", "dietary_restrictions": [], "medical_conditions": [], "experience_level": "advanced", "retreat_ids": ["ret-004", "ret-015"], "total_spent_usd": 3150.0},
        {"id": "par-013", "name": "Jennifer Kim", "email": "jen.k@email.com", "country": "US", "dietary_restrictions": ["vegan"], "medical_conditions": [], "experience_level": "intermediate", "retreat_ids": ["ret-007"], "total_spent_usd": 950.0},
        {"id": "par-014", "name": "Thomas Anderson", "email": "tom.a@email.com", "country": "UK", "dietary_restrictions": [], "medical_conditions": [], "experience_level": "beginner", "retreat_ids": ["ret-002", "ret-010"], "total_spent_usd": 1650.0},
        {"id": "par-015", "name": "Ana Sofia Perez", "email": "ana.p@email.com", "country": "CO", "dietary_restrictions": ["vegetarian"], "medical_conditions": [], "experience_level": "intermediate", "retreat_ids": ["ret-009", "ret-016"], "total_spent_usd": 1230.0},
        {"id": "par-016", "name": "Ryan O'Brien", "email": "ryan.ob@email.com", "country": "IE", "dietary_restrictions": [], "medical_conditions": [], "experience_level": "beginner", "retreat_ids": ["ret-012"], "total_spent_usd": 1100.0},
        {"id": "par-017", "name": "Yuki Tanaka", "email": "yuki.t@email.com", "country": "JP", "dietary_restrictions": ["vegan"], "medical_conditions": [], "experience_level": "advanced", "retreat_ids": ["ret-001", "ret-010"], "total_spent_usd": 2600.0},
        {"id": "par-018", "name": "Alexandra Petrov", "email": "alex.p@email.com", "country": "RO", "dietary_restrictions": [], "medical_conditions": [], "experience_level": "intermediate", "retreat_ids": ["ret-003"], "total_spent_usd": 800.0},
        {"id": "par-019", "name": "Diego Morales", "email": "diego.m@email.com", "country": "MX", "dietary_restrictions": [], "medical_conditions": [], "experience_level": "advanced", "retreat_ids": ["ret-004", "ret-011"], "total_spent_usd": 1100.0},
        {"id": "par-020", "name": "Emily Watson", "email": "emily.w@email.com", "country": "US", "dietary_restrictions": ["gluten_free", "dairy_free"], "medical_conditions": ["anxiety"], "experience_level": "beginner", "retreat_ids": ["ret-006"], "total_spent_usd": 1600.0},
        {"id": "par-021", "name": "Liam Murphy", "email": "liam.m@email.com", "country": "AU", "dietary_restrictions": [], "medical_conditions": [], "experience_level": "intermediate", "retreat_ids": ["ret-008"], "total_spent_usd": 3500.0},
        {"id": "par-022", "name": "Valentina Lopez", "email": "val.l@email.com", "country": "AR", "dietary_restrictions": ["vegetarian"], "medical_conditions": [], "experience_level": "beginner", "retreat_ids": ["ret-009"], "total_spent_usd": 550.0},
        {"id": "par-023", "name": "Benjamin Foster", "email": "ben.f@email.com", "country": "US", "dietary_restrictions": [], "medical_conditions": [], "experience_level": "intermediate", "retreat_ids": ["ret-007", "ret-013"], "total_spent_usd": 4150.0},
        {"id": "par-024", "name": "Camila Santos", "email": "camila.s@email.com", "country": "BR", "dietary_restrictions": ["vegan"], "medical_conditions": [], "experience_level": "advanced", "retreat_ids": ["ret-005"], "total_spent_usd": 2200.0},
        {"id": "par-025", "name": "Nathan Pierce", "email": "nathan.p@email.com", "country": "CA", "dietary_restrictions": [], "medical_conditions": ["diabetes_t1"], "experience_level": "beginner", "retreat_ids": ["ret-017"], "total_spent_usd": 600.0},
        {"id": "par-026", "name": "Clara Johansson", "email": "clara.j@email.com", "country": "SE", "dietary_restrictions": ["raw"], "medical_conditions": [], "experience_level": "intermediate", "retreat_ids": ["ret-001"], "total_spent_usd": 1400.0},
        {"id": "par-027", "name": "Roberto Fernandez", "email": "roberto.f@email.com", "country": "ES", "dietary_restrictions": [], "medical_conditions": [], "experience_level": "beginner", "retreat_ids": ["ret-018"], "total_spent_usd": 520.0},
        {"id": "par-028", "name": "Aisha Patel", "email": "aisha.p@email.com", "country": "UK", "dietary_restrictions": ["vegetarian", "no_alcohol"], "medical_conditions": [], "experience_level": "advanced", "retreat_ids": ["ret-013"], "total_spent_usd": 3200.0},
        {"id": "par-029", "name": "Martin Kowalski", "email": "martin.k@email.com", "country": "PL", "dietary_restrictions": [], "medical_conditions": [], "experience_level": "beginner", "retreat_ids": ["ret-002"], "total_spent_usd": 450.0},
        {"id": "par-030", "name": "Lucia Herrera", "email": "lucia.h@email.com", "country": "MX", "dietary_restrictions": [], "medical_conditions": [], "experience_level": "intermediate", "retreat_ids": ["ret-011", "ret-016"], "total_spent_usd": 1430.0},
    ]

    facilitators = [
        {"id": "fac-001", "name": "Sahajananda (Francisco)", "specialties": ["yoga", "meditation"], "certifications": ["E-RYT 500", "Hridaya Yoga Lineage"], "languages": ["es", "en", "ro"], "hourly_rate_usd": 80.0, "bio": "Founder of Hridaya Yoga. 20+ years teaching traditional yoga and meditation in Mazunte.", "rating": 4.9, "availability": "booked", "location": "mazunte"},
        {"id": "fac-002", "name": "Claudia Luna", "specialties": ["yoga", "breathwork"], "certifications": ["RYT-500", "Pranayama Specialist"], "languages": ["es", "en"], "hourly_rate_usd": 60.0, "bio": "Vinyasa and pranayama teacher with 12 years experience on the Oaxacan coast.", "rating": 4.7, "availability": "booked", "location": "mazunte"},
        {"id": "fac-003", "name": "Ajahn Sompong", "specialties": ["meditation"], "certifications": ["Vipassana Teacher", "Buddhist Studies MA"], "languages": ["en", "th", "es"], "hourly_rate_usd": 70.0, "bio": "Thai meditation teacher who has led Vipassana retreats in Oaxaca for 8 years.", "rating": 4.8, "availability": "available", "location": "zipolite"},
        {"id": "fac-004", "name": "Don Aurelio Cruz", "specialties": ["herbalism", "temazcal"], "certifications": ["Traditional Zapotec Healer"], "languages": ["es", "zapotec"], "hourly_rate_usd": 55.0, "bio": "5th generation Zapotec healer from the Valles Centrales. Specialist in limpia and herbal medicine.", "rating": 4.9, "availability": "available", "location": "hierve_el_agua"},
        {"id": "fac-005", "name": "Martha Rios", "specialties": ["herbalism", "reiki"], "certifications": ["Usui Reiki Master", "Herbalism Certificate"], "languages": ["es", "en"], "hourly_rate_usd": 45.0, "bio": "Reiki master and herbalist combining Japanese energy work with Oaxacan plant medicine.", "rating": 4.5, "availability": "available", "location": "oaxaca_city"},
        {"id": "fac-006", "name": "Maestra Sofia Jimenez", "specialties": ["temazcal", "herbalism"], "certifications": ["Indigenous Healers Cooperative", "Temazcalera 30+ years"], "languages": ["es", "zapotec"], "hourly_rate_usd": 50.0, "bio": "Respected temazcalera who has conducted over 3,000 ceremonies near Monte Alban.", "rating": 4.9, "availability": "available", "location": "monte_alban_area"},
        {"id": "fac-007", "name": "Dona Lupita Hernandez", "specialties": ["herbalism"], "certifications": ["Traditional Mazatec Medicine"], "languages": ["es", "mazatec"], "hourly_rate_usd": 75.0, "bio": "Mazatec curandera from the Sierra Norte. Guides plant medicine ceremonies with deep ancestral knowledge.", "rating": 4.8, "availability": "booked", "location": "san_jose_del_pacifico"},
        {"id": "fac-008", "name": "Rafael Vega", "specialties": ["meditation", "breathwork"], "certifications": ["Clinical Psychologist", "Integration Specialist"], "languages": ["es", "en"], "hourly_rate_usd": 90.0, "bio": "Clinical psychologist specializing in psychedelic integration and ceremonial support.", "rating": 4.6, "availability": "available", "location": "san_jose_del_pacifico"},
        {"id": "fac-009", "name": "Andrea Solano", "specialties": ["yoga", "massage"], "certifications": ["RYT-200", "Thai Massage Certificate"], "languages": ["es", "en"], "hourly_rate_usd": 55.0, "bio": "Combines yoga teaching with traditional Thai and Oaxacan massage techniques.", "rating": 4.6, "availability": "booked", "location": "oaxaca_city"},
        {"id": "fac-010", "name": "Chef Rosalba Mendoza", "specialties": ["herbalism"], "certifications": ["Culinary Arts Diploma", "Nutritional Therapy"], "languages": ["es", "en"], "hourly_rate_usd": 65.0, "bio": "Oaxacan chef and nutritional therapist. Creates wellness menus from traditional recipes.", "rating": 4.7, "availability": "available", "location": "oaxaca_city"},
        {"id": "fac-011", "name": "Jake Morrison", "specialties": ["breathwork", "yoga"], "certifications": ["Wim Hof Method Instructor", "RYT-200"], "languages": ["en", "es"], "hourly_rate_usd": 60.0, "bio": "Canadian breathwork facilitator based in Mazunte. Leads Wim Hof and holotropic sessions.", "rating": 4.5, "availability": "available", "location": "mazunte"},
        {"id": "fac-012", "name": "Gabriela Orozco", "specialties": ["yoga", "massage", "reiki"], "certifications": ["RYT-500", "Usui Reiki Level 2", "Swedish Massage"], "languages": ["es", "en", "de"], "hourly_rate_usd": 55.0, "bio": "Multi-disciplinary wellness practitioner at Bahias Wellness Huatulco.", "rating": 4.4, "availability": "available", "location": "huatulco"},
        {"id": "fac-013", "name": "Ixchel Ruiz", "specialties": ["sound_healing", "meditation"], "certifications": ["Sound Healing Academy", "Cacao Ceremony Facilitator"], "languages": ["es", "en"], "hourly_rate_usd": 50.0, "bio": "Sound healer and cacao ceremony facilitator. Uses crystal bowls, gongs, and traditional instruments.", "rating": 4.7, "availability": "available", "location": "mazunte"},
        {"id": "fac-014", "name": "Omar Sanchez", "specialties": ["sound_healing"], "certifications": ["Gong Master", "Music Therapy"], "languages": ["es", "en"], "hourly_rate_usd": 45.0, "bio": "Gong master and multi-instrumentalist creating immersive sound journeys.", "rating": 4.5, "availability": "available", "location": "zipolite"},
        {"id": "fac-015", "name": "Elena Ruiz", "specialties": ["herbalism", "reiki"], "certifications": ["Traditional Healer Network", "Usui Reiki Master"], "languages": ["es", "en"], "hourly_rate_usd": 50.0, "bio": "Cacao ceremony specialist and herbalist at Xocolatl Healing House.", "rating": 4.6, "availability": "available", "location": "oaxaca_city"},
    ]

    bookings = [
        {"id": "bk-001", "retreat_id": "ret-001", "participant_id": "par-001", "status": "paid", "amount_usd": 1400.0, "deposit_usd": 350.0, "payment_method": "card", "booking_date": "2026-03-01", "special_requests": "Bottom bunk please", "dietary_notes": "Strict vegan"},
        {"id": "bk-002", "retreat_id": "ret-001", "participant_id": "par-003", "status": "paid", "amount_usd": 1400.0, "deposit_usd": 350.0, "payment_method": "transfer", "booking_date": "2026-02-15", "special_requests": "", "dietary_notes": "Vegetarian"},
        {"id": "bk-003", "retreat_id": "ret-002", "participant_id": "par-004", "status": "confirmed", "amount_usd": 450.0, "deposit_usd": 150.0, "payment_method": "card", "booking_date": "2026-03-20", "special_requests": "", "dietary_notes": ""},
        {"id": "bk-004", "retreat_id": "ret-003", "participant_id": "par-005", "status": "paid", "amount_usd": 800.0, "deposit_usd": 200.0, "payment_method": "card", "booking_date": "2026-03-10", "special_requests": "Speaks fluent Zapotec", "dietary_notes": ""},
        {"id": "bk-005", "retreat_id": "ret-005", "participant_id": "par-007", "status": "paid", "amount_usd": 2200.0, "deposit_usd": 700.0, "payment_method": "transfer", "booking_date": "2026-03-15", "special_requests": "Previous ceremony experience", "dietary_notes": "Raw vegan"},
        {"id": "bk-006", "retreat_id": "ret-006", "participant_id": "par-002", "status": "checked_in", "amount_usd": 1600.0, "deposit_usd": 400.0, "payment_method": "card", "booking_date": "2026-03-01", "special_requests": "Ground floor room", "dietary_notes": ""},
        {"id": "bk-007", "retreat_id": "ret-008", "participant_id": "par-006", "status": "paid", "amount_usd": 3500.0, "deposit_usd": 1000.0, "payment_method": "card", "booking_date": "2026-02-20", "special_requests": "Ocean view room", "dietary_notes": "Gluten free"},
        {"id": "bk-008", "retreat_id": "ret-008", "participant_id": "par-008", "status": "paid", "amount_usd": 3500.0, "deposit_usd": 1000.0, "payment_method": "transfer", "booking_date": "2026-02-25", "special_requests": "", "dietary_notes": ""},
        {"id": "bk-009", "retreat_id": "ret-004", "participant_id": "par-012", "status": "confirmed", "amount_usd": 350.0, "deposit_usd": 100.0, "payment_method": "card", "booking_date": "2026-04-01", "special_requests": "", "dietary_notes": ""},
        {"id": "bk-010", "retreat_id": "ret-012", "participant_id": "par-009", "status": "paid", "amount_usd": 1100.0, "deposit_usd": 300.0, "payment_method": "card", "booking_date": "2026-03-05", "special_requests": "Surf board rental", "dietary_notes": "Vegetarian"},
        {"id": "bk-011", "retreat_id": "ret-013", "participant_id": "par-023", "status": "paid", "amount_usd": 3200.0, "deposit_usd": 800.0, "payment_method": "transfer", "booking_date": "2026-03-10", "special_requests": "", "dietary_notes": ""},
        {"id": "bk-012", "retreat_id": "ret-006", "participant_id": "par-010", "status": "checked_in", "amount_usd": 1600.0, "deposit_usd": 400.0, "payment_method": "card", "booking_date": "2026-03-15", "special_requests": "Extra pillow", "dietary_notes": ""},
        {"id": "bk-013", "retreat_id": "ret-001", "participant_id": "par-011", "status": "paid", "amount_usd": 1400.0, "deposit_usd": 350.0, "payment_method": "card", "booking_date": "2026-03-18", "special_requests": "", "dietary_notes": "Pescatarian"},
        {"id": "bk-014", "retreat_id": "ret-007", "participant_id": "par-013", "status": "confirmed", "amount_usd": 950.0, "deposit_usd": 250.0, "payment_method": "card", "booking_date": "2026-04-01", "special_requests": "", "dietary_notes": "Vegan"},
        {"id": "bk-015", "retreat_id": "ret-002", "participant_id": "par-014", "status": "paid", "amount_usd": 450.0, "deposit_usd": 150.0, "payment_method": "card", "booking_date": "2026-03-22", "special_requests": "", "dietary_notes": ""},
        {"id": "bk-016", "retreat_id": "ret-009", "participant_id": "par-015", "status": "pending", "amount_usd": 550.0, "deposit_usd": 150.0, "payment_method": "card", "booking_date": "2026-04-03", "special_requests": "", "dietary_notes": "Vegetarian"},
        {"id": "bk-017", "retreat_id": "ret-017", "participant_id": "par-025", "status": "paid", "amount_usd": 600.0, "deposit_usd": 200.0, "payment_method": "card", "booking_date": "2026-03-28", "special_requests": "Diabetic — needs fridge for insulin", "dietary_notes": "Low sugar"},
        {"id": "bk-018", "retreat_id": "ret-005", "participant_id": "par-024", "status": "paid", "amount_usd": 2200.0, "deposit_usd": 700.0, "payment_method": "transfer", "booking_date": "2026-03-20", "special_requests": "", "dietary_notes": "Vegan"},
        {"id": "bk-019", "retreat_id": "ret-019", "participant_id": "par-001", "status": "completed", "amount_usd": 400.0, "deposit_usd": 100.0, "payment_method": "card", "booking_date": "2026-02-28", "special_requests": "", "dietary_notes": "Vegan"},
        {"id": "bk-020", "retreat_id": "ret-013", "participant_id": "par-028", "status": "paid", "amount_usd": 3200.0, "deposit_usd": 800.0, "payment_method": "transfer", "booking_date": "2026-03-12", "special_requests": "No alcohol preference", "dietary_notes": "Vegetarian, no alcohol"},
        {"id": "bk-021", "retreat_id": "ret-018", "participant_id": "par-027", "status": "confirmed", "amount_usd": 520.0, "deposit_usd": 150.0, "payment_method": "card", "booking_date": "2026-04-02", "special_requests": "", "dietary_notes": ""},
        {"id": "bk-022", "retreat_id": "ret-011", "participant_id": "par-019", "status": "paid", "amount_usd": 750.0, "deposit_usd": 200.0, "payment_method": "card", "booking_date": "2026-04-01", "special_requests": "", "dietary_notes": ""},
        {"id": "bk-023", "retreat_id": "ret-020", "participant_id": "par-017", "status": "completed", "amount_usd": 120.0, "deposit_usd": 0.0, "payment_method": "cash", "booking_date": "2026-04-04", "special_requests": "", "dietary_notes": "Vegan"},
        {"id": "bk-024", "retreat_id": "ret-001", "participant_id": "par-026", "status": "paid", "amount_usd": 1400.0, "deposit_usd": 350.0, "payment_method": "transfer", "booking_date": "2026-03-25", "special_requests": "", "dietary_notes": "Raw food only"},
        {"id": "bk-025", "retreat_id": "ret-016", "participant_id": "par-030", "status": "pending", "amount_usd": 680.0, "deposit_usd": 180.0, "payment_method": "card", "booking_date": "2026-04-04", "special_requests": "", "dietary_notes": ""},
    ]

    services = [
        {"id": "svc-001", "name": "Aeropuerto Oaxaca Transfer", "type": "transportation", "provider": "Transportes Turisticos Oaxaca", "contact": "+52-951-200-0001", "price_range_usd": {"min": 25, "max": 60}, "description": "Airport pickup/dropoff to Oaxaca city hotels and nearby retreat centers.", "rating": 4.5, "location": "oaxaca_city"},
        {"id": "svc-002", "name": "Costa Oaxaquena Shuttle", "type": "transportation", "provider": "Pacific Coast Transfers", "contact": "+52-958-200-0002", "price_range_usd": {"min": 40, "max": 120}, "description": "Shared and private shuttles from Oaxaca city to Mazunte, Zipolite, Huatulco coast.", "rating": 4.3, "location": "mazunte"},
        {"id": "svc-003", "name": "Cocina Tradicional Oaxaquena", "type": "catering", "provider": "Chef Rosalba Mendoza", "contact": "+52-951-200-0003", "price_range_usd": {"min": 15, "max": 35}, "description": "Traditional Oaxacan wellness catering: tlayudas, mole, chapulines, organic salads. Per person/day.", "rating": 4.8, "location": "oaxaca_city"},
        {"id": "svc-004", "name": "Hierve el Agua Excursion", "type": "excursion", "provider": "Oaxaca Adventures", "contact": "+52-951-200-0004", "price_range_usd": {"min": 35, "max": 65}, "description": "Full day trip to petrified waterfalls. Includes transport, guide, and mezcal tasting stop.", "rating": 4.6, "location": "hierve_el_agua"},
        {"id": "svc-005", "name": "Monte Alban Sunrise Tour", "type": "excursion", "provider": "Zapotec Heritage Tours", "contact": "+52-951-200-0005", "price_range_usd": {"min": 40, "max": 80}, "description": "Early morning visit to the Zapotec ruins. Includes meditation session at the ancient site.", "rating": 4.7, "location": "monte_alban_area"},
        {"id": "svc-006", "name": "Temazcal Ceremony Materials", "type": "ceremony", "provider": "Herbolaria Monte Alban", "contact": "+52-951-200-0006", "price_range_usd": {"min": 20, "max": 50}, "description": "Sacred herbs, volcanic stones, and traditional materials for temazcal ceremonies.", "rating": 4.8, "location": "monte_alban_area"},
        {"id": "svc-007", "name": "Retreat Photography & Video", "type": "photography", "provider": "Luz Oaxaca Media", "contact": "+52-951-200-0007", "price_range_usd": {"min": 150, "max": 500}, "description": "Professional photo and video packages for retreats. Drone footage available.", "rating": 4.4, "location": "oaxaca_city"},
        {"id": "svc-008", "name": "Mazunte Eco-Cabanas", "type": "accommodation", "provider": "Cabanas del Pacifico", "contact": "+52-958-200-0008", "price_range_usd": {"min": 30, "max": 80}, "description": "Eco-friendly overflow accommodation near Mazunte retreat centers. Per night.", "rating": 4.2, "location": "mazunte"},
        {"id": "svc-009", "name": "Organic Farm-to-Table Catering", "type": "catering", "provider": "Huerto Mazunte", "contact": "+52-958-200-0009", "price_range_usd": {"min": 18, "max": 40}, "description": "Organic vegan/vegetarian catering from local permaculture farm. Per person/day.", "rating": 4.7, "location": "mazunte"},
        {"id": "svc-010", "name": "Mezcal & Textile Tour", "type": "excursion", "provider": "Oaxaca Cultural Experiences", "contact": "+52-951-200-0010", "price_range_usd": {"min": 45, "max": 90}, "description": "Visit artisan mezcal palenque and Zapotec textile workshop in Teotitlan del Valle.", "rating": 4.5, "location": "oaxaca_city"},
    ]

    reviews = [
        {"id": "rev-001", "retreat_id": "ret-019", "participant_id": "par-001", "rating": 5.0, "comment": "The Spring Equinox festival was magical. Hridaya's teaching is transformative. Mazunte sunsets during meditation were unforgettable.", "aspects": {"instruction": 5.0, "accommodation": 4.0, "food": 4.5, "location": 5.0, "value": 4.5}, "date": "2026-03-23"},
        {"id": "rev-002", "retreat_id": "ret-019", "participant_id": "par-003", "rating": 4.5, "comment": "Excellent teachers and beautiful setting. Camping was basic but the yoga was world-class.", "aspects": {"instruction": 5.0, "accommodation": 3.5, "food": 4.5, "location": 5.0, "value": 4.5}, "date": "2026-03-24"},
        {"id": "rev-003", "retreat_id": "ret-020", "participant_id": "par-017", "rating": 4.0, "comment": "Beautiful full moon meditation on Zipolite beach. Sound bath was incredible. Would prefer longer format.", "aspects": {"instruction": 4.5, "accommodation": 3.0, "food": 3.0, "location": 5.0, "value": 4.0}, "date": "2026-04-06"},
        {"id": "rev-004", "retreat_id": "ret-019", "participant_id": "par-011", "rating": 5.0, "comment": "Mon experience la plus profonde. Les enseignants sont authentiques et le lieu est sacre.", "aspects": {"instruction": 5.0, "accommodation": 4.0, "food": 5.0, "location": 5.0, "value": 5.0}, "date": "2026-03-23"},
        {"id": "rev-005", "retreat_id": "ret-020", "participant_id": "par-014", "rating": 4.5, "comment": "Ajahn Sompong is a genuine teacher. The beach setting adds something special to Vipassana practice.", "aspects": {"instruction": 5.0, "accommodation": 3.5, "food": 3.5, "location": 5.0, "value": 4.5}, "date": "2026-04-07"},
        {"id": "rev-006", "retreat_id": "ret-019", "participant_id": "par-023", "rating": 4.0, "comment": "Great energy and variety of teachers. Got a bit crowded at 38 people. Food was amazing.", "aspects": {"instruction": 4.5, "accommodation": 3.5, "food": 5.0, "location": 4.5, "value": 4.0}, "date": "2026-03-25"},
        {"id": "rev-007", "retreat_id": "ret-019", "participant_id": "par-026", "rating": 5.0, "comment": "Livet forandrande upplevelse. Claudia's breathwork session opened something deep.", "aspects": {"instruction": 5.0, "accommodation": 4.0, "food": 4.0, "location": 5.0, "value": 5.0}, "date": "2026-03-24"},
        {"id": "rev-008", "retreat_id": "ret-020", "participant_id": "par-004", "rating": 3.5, "comment": "Good meditation but the one-night format felt rushed. Beach was beautiful for practice.", "aspects": {"instruction": 4.0, "accommodation": 3.0, "food": 2.5, "location": 5.0, "value": 3.5}, "date": "2026-04-06"},
        {"id": "rev-009", "retreat_id": "ret-019", "participant_id": "par-009", "rating": 4.5, "comment": "Bellissimo! The combination of yoga festival and beach was perfect. Met wonderful people from everywhere.", "aspects": {"instruction": 4.5, "accommodation": 4.0, "food": 4.5, "location": 5.0, "value": 4.5}, "date": "2026-03-23"},
        {"id": "rev-010", "retreat_id": "ret-020", "participant_id": "par-029", "rating": 4.0, "comment": "Peaceful experience. Omar's gong playing was exceptional. Wish there was food included.", "aspects": {"instruction": 4.0, "accommodation": 3.5, "food": 2.0, "location": 4.5, "value": 4.0}, "date": "2026-04-07"},
        {"id": "rev-011", "retreat_id": "ret-019", "participant_id": "par-016", "rating": 4.5, "comment": "Brilliant craic! Never done yoga before but the teachers made everyone feel welcome.", "aspects": {"instruction": 5.0, "accommodation": 3.5, "food": 4.5, "location": 5.0, "value": 4.5}, "date": "2026-03-24"},
        {"id": "rev-012", "retreat_id": "ret-019", "participant_id": "par-012", "rating": 5.0, "comment": "Como oaxaqueno, me enorgullece ver nuestras tradiciones compartidas con respeto. Excelente evento.", "aspects": {"instruction": 5.0, "accommodation": 4.0, "food": 5.0, "location": 5.0, "value": 5.0}, "date": "2026-03-23"},
        {"id": "rev-013", "retreat_id": "ret-020", "participant_id": "par-022", "rating": 4.0, "comment": "Hermosa noche de luna llena. La meditacion en la playa fue muy especial.", "aspects": {"instruction": 4.0, "accommodation": 3.0, "food": 3.0, "location": 5.0, "value": 4.0}, "date": "2026-04-06"},
        {"id": "rev-014", "retreat_id": "ret-019", "participant_id": "par-005", "rating": 5.0, "comment": "La energia del equinoccio en Mazunte es unica. Los maestros honran la tradicion ancestral.", "aspects": {"instruction": 5.0, "accommodation": 4.0, "food": 5.0, "location": 5.0, "value": 5.0}, "date": "2026-03-24"},
        {"id": "rev-015", "retreat_id": "ret-019", "participant_id": "par-021", "rating": 4.0, "comment": "Amazing location and teachers. Long trip from Australia but totally worth it. Would come back for the 7-day.", "aspects": {"instruction": 4.5, "accommodation": 3.5, "food": 4.0, "location": 5.0, "value": 4.0}, "date": "2026-03-25"},
    ]

    pricing = [
        {"id": "sp-001", "center_id": "ctr-mazunte-01", "season": "peak_winter", "multiplier": 1.5, "start_month": 11, "end_month": 2, "notes": "High season: Nov-Feb. North American/European winter escape."},
        {"id": "sp-002", "center_id": "ctr-mazunte-01", "season": "shoulder_spring", "multiplier": 1.2, "start_month": 3, "end_month": 5, "notes": "Spring shoulder season. Still good weather, fewer crowds."},
        {"id": "sp-003", "center_id": "ctr-mazunte-01", "season": "low_summer", "multiplier": 0.8, "start_month": 6, "end_month": 8, "notes": "Rainy season. Humidity high on coast. Lower demand."},
        {"id": "sp-004", "center_id": "ctr-mazunte-01", "season": "peak_fall", "multiplier": 1.1, "start_month": 9, "end_month": 10, "notes": "Fall pickup. Day of the Dead season begins."},
        {"id": "sp-005", "center_id": "ctr-huatulco-01", "season": "peak_winter", "multiplier": 1.6, "start_month": 11, "end_month": 2, "notes": "Premium winter rates for luxury resort."},
        {"id": "sp-006", "center_id": "ctr-huatulco-01", "season": "shoulder_spring", "multiplier": 1.3, "start_month": 3, "end_month": 5, "notes": "Spring rates. Easter week peak within shoulder."},
        {"id": "sp-007", "center_id": "ctr-huatulco-01", "season": "low_summer", "multiplier": 0.7, "start_month": 6, "end_month": 8, "notes": "Hurricane season discounts."},
        {"id": "sp-008", "center_id": "ctr-huatulco-01", "season": "peak_fall", "multiplier": 1.0, "start_month": 9, "end_month": 10, "notes": "Transition season, standard rates."},
        {"id": "sp-009", "center_id": "ctr-sanjose-01", "season": "peak_winter", "multiplier": 1.3, "start_month": 11, "end_month": 2, "notes": "Dry season in mountains. Best weather for ceremonies."},
        {"id": "sp-010", "center_id": "ctr-sanjose-01", "season": "low_summer", "multiplier": 0.9, "start_month": 6, "end_month": 8, "notes": "Rainy but mystical cloud forest atmosphere."},
        {"id": "sp-011", "center_id": "ctr-hierve-01", "season": "peak_winter", "multiplier": 1.4, "start_month": 11, "end_month": 2, "notes": "Dry season. Perfect for outdoor healing sessions."},
        {"id": "sp-012", "center_id": "ctr-hierve-01", "season": "low_summer", "multiplier": 0.85, "start_month": 6, "end_month": 8, "notes": "Rainy season. Mineral springs still accessible."},
        {"id": "sp-013", "center_id": "ctr-oaxaca-01", "season": "peak_winter", "multiplier": 1.3, "start_month": 11, "end_month": 2, "notes": "Tourist high season in Oaxaca city."},
        {"id": "sp-014", "center_id": "ctr-oaxaca-01", "season": "peak_fall", "multiplier": 1.4, "start_month": 9, "end_month": 10, "notes": "Day of the Dead / Guelaguetza overflow. Highest demand."},
        {"id": "sp-015", "center_id": "ctr-zipolite-01", "season": "peak_winter", "multiplier": 1.4, "start_month": 11, "end_month": 2, "notes": "Beach high season."},
        {"id": "sp-016", "center_id": "ctr-zipolite-01", "season": "low_summer", "multiplier": 0.75, "start_month": 6, "end_month": 8, "notes": "Very hot + rainy. Lowest beach rates."},
    ]

    insights = [
        {"id": "ins-001", "insight_type": "booking_trend", "title": "Yoga retreats dominate Q1 bookings", "description": "7-day yoga retreats account for 45% of all Q1 2026 bookings. Hridaya and teacher training programs are the top revenue drivers. Consider expanding yoga offering at coast locations.", "priority": "high"},
        {"id": "ins-002", "insight_type": "pricing", "title": "Luxury segment underpriced at Huatulco", "description": "Bahias Wellness Huatulco luxury retreats are priced 20% below comparable resorts in Riviera Maya. Market analysis suggests $4000-4500 is achievable for 10-day packages.", "priority": "high"},
        {"id": "ins-003", "insight_type": "demand", "title": "Growing demand for temazcal + healing combo", "description": "Search trends show 60% YoY increase in 'temazcal oaxaca' and 'traditional healing mexico'. Current supply of dedicated healing retreats is limited to 3 centers.", "priority": "medium"},
        {"id": "ins-004", "insight_type": "seasonal", "title": "Rainy season opportunity in mountains", "description": "San Jose del Pacifico cloud forest retreats maintain 70% occupancy even in rainy season due to the mystical atmosphere. Consider promoting mountain retreats as rainy-season alternative to coast.", "priority": "medium"},
        {"id": "ins-005", "insight_type": "facilitator_gap", "title": "Shortage of bilingual meditation teachers", "description": "Only 2 facilitators offer meditation instruction in English. International participants (65% of bookings) need English-speaking guides. Recruiting bilingual teachers could increase capacity 30%.", "priority": "high"},
        {"id": "ins-006", "insight_type": "booking_trend", "title": "Corporate wellness emerging segment", "description": "Corporate retreat bookings up 3x since 2025. Huatulco and Oaxaca city centers best positioned. Average corporate group spend is $12,000-15,000 per event.", "priority": "medium"},
    ]

    store = {
        "centers": centers,
        "retreats": retreats,
        "participants": participants,
        "facilitators": facilitators,
        "bookings": bookings,
        "services": services,
        "reviews": reviews,
        "pricing": pricing,
        "insights": insights,
    }
    save_store(store)
    return store
